name = "packages"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# description = "A Gleam library..."
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

gleam = ">= 1.6.0"

[dependencies]
gleam_stdlib = "~> 0.23"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_hackney = "~> 1.0"
gleam_erlang = "~> 0.18"
mist = ">= 4.0.7 and < 5.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_otp = ">= 0.5.0 and < 1.0.0"
gleam_hexpm = ">= 3.0.0 and < 4.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
lustre = "~> 4.6.1"
argv = "~> 1.0"
wisp = ">= 1.2.0 and < 2.0.0"
storail = ">= 3.0.0 and < 4.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleamsver = ">= 1.0.1 and < 2.0.0"
porter_stemmer = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
