name = "packages"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# description = "A Gleam library..."
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

internal_modules = [
  "packages/internal",
  "packages/internal/*",
  "packages/generated/*",
]

[dependencies]
gleam_stdlib = "~> 0.23"
gleam_json = "~> 0.5"
gleam_hackney = "~> 1.0"
gleam_erlang = "~> 0.18"
birl = "~> 0.11"
mist = "~> 0.10"
gleam_http = "~> 3.1"
nakai = "~> 0.4"
gleam_otp = "~> 0.5"
gleam_hexpm = "~> 0.1"
sqlight = "~> 0.8"
simplifile = "~> 0.1"
wisp = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.7"
